packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.66.5
  eslint: ^9
  prettier: ^3.5.0
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.1
  react: ^19
  react-dom: ^19.0.0
  "@types/node": ^22
  "@types/react": ^19
  "@types/react-dom": ^19
